function report=verify_dsc_likelihood(run_dir)
%VERIFY_DSC_LIKELIHOOD Independently check a saved completed sampler state.
% Reads the checkpoint without advancing or changing its chain. The only
% output written is final_likelihood_validation.json in the supplied run.
root=fileparts(mfilename('fullpath'));
addpath(fullfile(root,'toolbox'));
loaded=load(fullfile(run_dir,'checkpoint.mat'),'checkpoint'); cp=loaded.checkpoint;
assert(isfield(cp.identity,'implementation'),'dsc:ValidationIdentity', ...
    'The checkpoint must record its numerical implementation.');
backend=cp.identity.implementation.correlation_backend;
current_implementation=dsc_sampler_signature(backend);
assert(isequaln(current_implementation,cp.identity.implementation), ...
    'dsc:ValidationIdentity','Sampler sources, native binary or MATLAB environment have changed.');
assert(cp.completed>=1 && numel(cp.diagnostics.loglik)==cp.completed, ...
    'dsc:ValidationState','A completed sweep with a saved likelihood is required.');
threads=cp.identity.cfg.correlation_threads;
Y=cp.identity.returns; mask=logical(cp.identity.mask); [T,m]=size(Y);
assert(isequal(size(mask),[T,m]) && isequal(size(cp.state.B),[T,m]) && ...
    isequal(size(cp.state.h),[T,m]) && isequal(size(cp.state.r),[T,m*(m-1)/2]), ...
    'dsc:ValidationShape','Checkpoint panel and latent-state dimensions differ.');
assert(all(isfinite(Y(mask))) && all(isfinite(cp.state.B(:))) && ...
    all(isfinite(cp.state.h(:))) && all(isfinite(cp.state.r(:))), ...
    'dsc:ValidationState','Observed returns and latent states must be finite.');

rng_before=rng;
% Never use returns outside the observed subspace: they may contain NaN/Inf.
Z=zeros(T,m);
Z(mask)=(Y(mask)-cp.state.B(mask)).*exp(-cp.state.h(mask)/2);
assert(all(isfinite(Z(mask))),'dsc:ValidationState', ...
    'Observed standardized residuals must be finite.');

reference_loglik=0; x=[];
for t=1:T
    % Original MATLAB reconstruction plus an explicit observed-space solve.
    [C,~,x]=dsc_corr_matrix(cp.state.r(t,:),x);
    ix=find(mask(t,:));
    if isempty(ix), continue; end
    L=chol(C(ix,ix),'lower'); u=L\Z(t,ix)';
    reference_loglik=reference_loglik-.5*(numel(ix)*log(2*pi)+ ...
        sum(cp.state.h(t,ix))+2*sum(log(diag(L)))+u'*u);
end
if strcmp(backend,'mex')
    constant=-.5*(nnz(mask)*log(2*pi)+sum(cp.state.h(mask)));
    backend_loglik=dsc_corr_batch_mex(cp.state.r,Z,mask,threads)+constant;
elseif strcmp(backend,'matlab')
    backend_loglik=reference_loglik;
else
    error('dsc:ValidationBackend','Unsupported saved correlation backend: %s',backend);
end
saved_loglik=cp.diagnostics.loglik(end);
errors=struct('backend_vs_matlab',abs(backend_loglik-reference_loglik), ...
    'saved_vs_matlab',abs(saved_loglik-reference_loglik), ...
    'saved_vs_backend',abs(saved_loglik-backend_loglik));
tolerance=1e-5;
assert(all(isfinite([reference_loglik backend_loglik saved_loglik])) && ...
    all(structfun(@(v)isfinite(v)&&v<tolerance,errors)), ...
    'dsc:LikelihoodMismatch','Final-state likelihoods disagree beyond %.1g.',tolerance);
assert(isequal(rng,rng_before),'dsc:ValidationRng', ...
    'Likelihood validation must not consume random draws.');

report=struct('status','passed', ...
    'purpose','Read-only numerical check of the last completed warm-up state; no posterior inference', ...
    'completed_iterations',cp.completed,'T',T,'m',m,'pairs',m*(m-1)/2, ...
    'observed_return_cells',nnz(mask),'masked_return_cells',nnz(~mask), ...
    'first_date',char(string(cp.identity.dates(1),'yyyy-MM-dd')), ...
    'last_date',char(string(cp.identity.dates(end),'yyyy-MM-dd')), ...
    'tickers',cp.identity.tickers,'source_hash',cp.identity.source_hash, ...
    'correlation_backend',backend,'correlation_threads',threads, ...
    'reference_full_loglik',reference_loglik,'backend_full_loglik',backend_loglik, ...
    'saved_full_loglik',saved_loglik,'absolute_errors',errors, ...
    'absolute_tolerance',tolerance,'rng_unchanged',true, ...
    'implementation',current_implementation);
output=fullfile(run_dir,'final_likelihood_validation.json');
fid=fopen(output,'w');
assert(fid>=0,'dsc:ValidationWrite','Cannot write final likelihood validation.');
guard=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
