function cfg = weekly_config()
%WEEKLY_CONFIG Reproducible defaults for the staged weekly research workflow.
root = fileparts(mfilename('fullpath'));
cfg.source_file = fullfile(root,'data','yad_tickers_no_usdcnh_from_20030804.csv');
cfg.start_date = '2003-08-04';
cfg.closure_policy = 'asof';
cfg.output_root = fullfile(root,'outputs','weekly_research');
cfg.freq = 'weekly';
cfg.p = 0;
cfg.seed = 20260911;
cfg.chain_id = 1;
cfg.num_chains = 1;
cfg.parallel_chains = false; % true requires Parallel Computing Toolbox.
cfg.convergence_mode = 'report'; % 'off' or 'report'.
cfg.auto_extend = false;
cfg.check_every = 250; % Retained draws per chain between diagnostic checks.
cfg.max_retained_draws = 2000; % Per-chain cap when auto_extend=true.
cfg.min_diagnostic_draws = 100;
cfg.rhat_threshold = 1.01;
cfg.min_ess = 400;
cfg.max_mcse_ratio = 0.05;
cfg.prior_weeks = 104; % Initial-prior weeks reserved and excluded from the likelihood.
cfg.shrinkage = 0.05;
cfg.calibration_windows = [52 104 156];
cfg.calibration_window = 104;
cfg.ig_shape = 10;
cfg.kB = 0.01;
cfg.max_iterations = 20;
cfg.max_seconds = 1800;
cfg.burnin = 20; % Every draw in the initial pilot is warm-up.
cfg.thin = 1;
cfg.chunk_size = 10;
cfg.resume = false;
cfg.estimate_parameters = true; % false: load saved parameters and smooth states only.
cfg.estimation_end_date = ''; % Optional yyyy-MM-dd cutoff; empty uses the latest week.
cfg.parameter_dir = ''; % Empty resolves to output_root/parameters.
cfg.parameter_file = ''; % Empty loads the latest timestamped parameter file.
cfg.parameter_smoothing = 'mean'; % 'mean' uses posterior means; 'draws' propagates saved parameter draws.
cfg.correlation_backend = 'auto'; % Use the validated MEX kernel if built; otherwise MATLAB.
cfg.correlation_threads = 4; % Per chain: account for num_chains when running in parallel.
end
